# Generated by Django 4.1.5 on 2023-06-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=500)),
                ('findings', models.CharField(max_length=300)),
                ('drugs_assigned', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Labtechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NursesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_Pressure', models.CharField(max_length=10)),
                ('Weight', models.CharField(max_length=10)),
                ('Temperature', models.CharField(max_length=10)),
                ('Pulse_rate', models.CharField(max_length=10)),
            ],
        ),
    ]
