# Generated by Django 4.1.3 on 2023-06-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Date_of_Appointment', models.DateField()),
                ('Time_of_Appointment', models.TimeField()),
                ('Doctor_Assigned_to', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Patient_type', models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('COOPERATE', 'COOPERATE')], max_length=10)),
                ('Patient_ID', models.IntegerField()),
                ('Date_Of_Birth', models.DateField()),
                ('Gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=7)),
                ('Location', models.CharField(max_length=30)),
                ('Tel', models.IntegerField()),
                ('Blood_Pressure', models.CharField(max_length=10)),
                ('Weight', models.CharField(max_length=10)),
                ('Temperature', models.CharField(max_length=10)),
                ('Pulse_rate', models.CharField(max_length=10)),
                ('Height', models.CharField(max_length=10)),
                ('results', models.CharField(max_length=200)),
                ('complaints', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=500)),
                ('findings', models.CharField(max_length=300)),
                ('drugs_assigned', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Patient_type', models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('COOPERATE', 'COOPERATE')], max_length=10)),
                ('Date_Of_Birth', models.DateField()),
                ('Gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=7)),
                ('Location', models.CharField(max_length=30)),
                ('Tel', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='nursespage',
            name='Height',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
