# Generated by Django 4.1.3 on 2023-06-23 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0003_alter_appointment_doctor_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Doctor_Assigned_to',
            field=models.ForeignKey(limit_choices_to={'groups': '8'}, max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Name',
            field=models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, to='dashboards.registrationpage'),
        ),
    ]
