# Generated by Django 4.1.3 on 2023-06-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_alter_appointment_doctor_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='Blood_Pressure',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='Pulse_rate',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='Temperature',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='complaints',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='drugs_assigned',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='results',
        ),
        migrations.AddField(
            model_name='nursespage',
            name='Name',
            field=models.ForeignKey(max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.registrationpage'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='Name',
            field=models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, to='dashboards.registrationpage'),
        ),
    ]
