# Generated by Django 4.1.3 on 2023-06-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_remove_patientdata_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Name',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.registrationpage')),
            ],
        ),
    ]
