# Generated by Django 4.1.3 on 2023-06-28 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_checkin_doctorassigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors', models.ForeignKey(max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.registrationpage')),
            ],
        ),
    ]
