# Generated by Django 4.1.3 on 2023-06-28 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0008_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doctors',
            field=models.ForeignKey(limit_choices_to={'groups': '8'}, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
