# Generated by Django 4.1.3 on 2023-06-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_alter_checkin_doctorassigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
