# Generated by Django 4.1.3 on 2023-06-28 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_alter_checkin_check_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.registrationpage'),
        ),
    ]
