# Generated by Django 4.1.3 on 2023-06-29 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_alter_checkin_doctorassigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursespage',
            name='Name',
        ),
        migrations.AddField(
            model_name='doctorpage',
            name='Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.nursespage'),
        ),
        migrations.AddField(
            model_name='labtechnician',
            name='Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.doctorpage'),
        ),
        migrations.AddField(
            model_name='nursespage',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.checkin'),
        ),
    ]
